Nagios NRPE Sachen nach "nrpe" Cookbook verschoben und umorganisiert.

diff --git a/chef/cookbooks/nrpe/files/default/nagios/plugin-scripts/check_glusterfs b/chef/cookbooks/nrpe/files/default/nagios/plugin-scripts/check_glusterfs
--- a/chef/cookbooks/nrpe/files/default/nagios/plugin-scripts/check_glusterfs
+++ b/chef/cookbooks/nrpe/files/default/nagios/plugin-scripts/check_glusterfs
@@ -52,37 +52,37 @@ if [ -z "${VOLUME}" -o -z "${BRICKS}" ]; then
 fi
 
 Exit () {
-	$ECHO "$1: ${2:0}"
-	status=STATE_$1
-	exit ${!status}
+    $ECHO "$1: ${2:0}"
+    status=STATE_$1
+    exit ${!status}
 }
 
 # check for commands
 for cmd in basename awk sudo pidof gluster; do
-	if ! type -p "$cmd" >/dev/null; then
-		Exit UNKNOWN "$cmd not found"
-	fi
+    if ! type -p "$cmd" >/dev/null; then
+        Exit UNKNOWN "$cmd not found"
+    fi
 done
 
 # check for glusterd (management daemon)
 if ! pidof glusterd &>/dev/null; then
-	Exit CRITICAL "glusterd management daemon not running"
+    Exit CRITICAL "glusterd management daemon not running"
 fi
 
 # check for glusterfsd (brick daemon)
 if ! pidof glusterfsd &>/dev/null; then
-	Exit CRITICAL "glusterfsd brick daemon not running"
+    Exit CRITICAL "glusterfsd brick daemon not running"
 fi
 
 # get volume heal status
 heal=0
 for entries in $(sudo gluster volume heal ${VOLUME} info | awk '/^Number of entries: /{print $4}'); do
-	if [ "$entries" -gt 0 ]; then
-		let $((heal+=entries))
-	fi
+    if [ "$entries" -gt 0 ]; then
+        let $((heal+=entries))
+    fi
 done
 if [ "$heal" -gt 0 ]; then
-	errors=("${errors[@]}" "$heal unsynched entries")
+    errors=("${errors[@]}" "$heal unsynched entries")
 fi
 
 # get volume status
@@ -90,62 +90,62 @@ bricksfound=0
 freegb=9999999
 shopt -s nullglob
 while read -r line; do
-	field=($(echo $line))
-	case ${field[0]} in
-	Brick) 
-		brick=${field[@]:2}
-		;;
-	Disk)
-		key=${field[@]:0:3}
-		if [ "${key}" = "Disk Space Free" ]; then
-			freeunit=${field[@]:4}
-			free=${freeunit:0:-2}
-			unit=${freeunit#$free}
-			if [ "$unit" != "GB" ]; then
-				Exit UNKNOWN "unknown disk space size $freeunit"
-			fi
-			#free=$(echo "${free} / 1" | bc -q)
-			#echo "################### free: $free"
-			free=${free%.*}
-			if [ $free -lt $freegb ]; then
-				freegb=$free
-			fi
-		fi
-		;;
-	Online)
-		online=${field[@]:2}
-		if [ "${online}" = "Y" ]; then
-			let $((bricksfound++))
-		else
-			errors=("${errors[@]}" "$brick offline")
-		fi
-		;;
-	esac
+    field=($(echo $line))
+    case ${field[0]} in
+    Brick) 
+        brick=${field[@]:2}
+        ;;
+    Disk)
+        key=${field[@]:0:3}
+        if [ "${key}" = "Disk Space Free" ]; then
+            freeunit=${field[@]:4}
+            free=${freeunit:0:-2}
+            unit=${freeunit#$free}
+            if [ "$unit" != "GB" ]; then
+                Exit UNKNOWN "unknown disk space size $freeunit"
+            fi
+            #free=$(echo "${free} / 1" | bc -q)
+            #echo "################### free: $free"
+            free=${free%.*}
+            if [ $free -lt $freegb ]; then
+                freegb=$free
+            fi
+        fi
+        ;;
+    Online)
+        online=${field[@]:2}
+        if [ "${online}" = "Y" ]; then
+            let $((bricksfound++))
+        else
+            errors=("${errors[@]}" "$brick offline")
+        fi
+        ;;
+    esac
 done < <(sudo gluster volume status ${VOLUME} detail)
 
 if [ $bricksfound -eq 0 ]; then
-	Exit CRITICAL "no bricks found"
+    Exit CRITICAL "no bricks found"
 elif [ $bricksfound -lt $BRICKS ]; then
-	errors=("${errors[@]}" "found $bricksfound bricks, expected $BRICKS ")
+    errors=("${errors[@]}" "found $bricksfound bricks, expected $BRICKS ")
 fi
 
 if [ -n "$CRIT" -a -n "$WARN" ]; then
-	if [ $CRIT -ge $WARN ]; then
-		Exit UNKNOWN "critical threshold below warning"
-	elif [ $freegb -lt $CRIT ]; then
-		Exit CRITICAL "free space ${freegb}GB"
-	elif [ $freegb -lt $WARN ]; then
-		errors=("${errors[@]}" "free space ${freegb}GB")
-	fi
+    if [ $CRIT -ge $WARN ]; then
+        Exit UNKNOWN "critical threshold below warning"
+    elif [ $freegb -lt $CRIT ]; then
+        Exit CRITICAL "free space ${freegb}GB"
+    elif [ $freegb -lt $WARN ]; then
+        errors=("${errors[@]}" "free space ${freegb}GB")
+    fi
 fi
 
 # exit with warning if errors
 if [ -n "$errors" ]; then
-	sep='; '
-	msg=$(printf "${sep}%s" "${errors[@]}")
-	msg=${msg:${#sep}}
+    sep='; '
+    msg=$(printf "${sep}%s" "${errors[@]}")
+    msg=${msg:${#sep}}
 
-	Exit WARNING "${msg}"
+    Exit WARNING "${msg}"
 fi
 
 # exit with no errors
